/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
package org.apache.xtable.spark;

import java.net.URI;
import java.util.List;
import java.util.Optional;
import java.util.function.UnaryOperator;
import java.util.stream.Collectors;

import lombok.extern.log4j.Log4j2;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.Path;
import org.apache.spark.sql.SparkSession;
import org.apache.spark.sql.catalyst.TableIdentifier;
import org.apache.spark.sql.catalyst.catalog.CatalogTable;
import org.apache.spark.sql.execution.QueryExecution;
import org.apache.spark.sql.util.QueryExecutionListener;

/**
 * Driver-side {@link QueryExecutionListener} that runs an incremental XTable sync after a
 * successful write to a configured source table. Register it via {@code
 * spark.sql.queryExecutionListeners=org.apache.xtable.spark.XTableSyncListener} and declare the
 * tables through {@code spark.xtable.*} (see {@link XTableSparkConfig}).
 *
 * <p>The listener is stateless apart from the immutable parsed config: the sync watermark lives in
 * the target's metadata, and the sync runs inline on the callback (see RFC-3 for the execution
 * model). It triggers only on recognized write commands whose output path matches a configured
 * table, so reads and writes to other tables are ignored.
 */
@Log4j2
public class XTableSyncListener implements QueryExecutionListener {

  private static final ThreadLocal<Boolean> SYNCING = ThreadLocal.withInitial(() -> Boolean.FALSE);

  private final XTableSyncService syncService = new XTableSyncService();
  private volatile List<TableSyncSpec> specs;

  @Override
  public void onSuccess(String funcName, QueryExecution qe, long durationNs) {
    if (SYNCING.get()) {
      // Ignore writes generated by our own sync running inline on this thread.
      return;
    }
    Optional<String> writtenPath = PlanTargetResolver.resolveWrittenPath(qe);
    if (!writtenPath.isPresent()) {
      return;
    }
    SparkSession session = activeSession();
    if (session == null) {
      return;
    }
    List<TableSyncSpec> matched =
        specs(session).stream()
            .filter(spec -> pathsMatch(writtenPath.get(), spec.getBasePath()))
            .collect(Collectors.toList());
    if (matched.isEmpty()) {
      log.debug("Write to {} did not match any configured spark.xtable table", writtenPath.get());
      return;
    }
    Configuration hadoopConf = session.sparkContext().hadoopConfiguration();
    SYNCING.set(Boolean.TRUE);
    try {
      for (TableSyncSpec spec : matched) {
        try {
          syncService.sync(spec, hadoopConf);
        } catch (Throwable t) {
          // Isolate failures so one table does not stop the others and a listener never
          // destabilizes Spark's listener bus; the next commit self-heals.
          log.error("XTable sync failed for table {} at {}", spec.getKey(), spec.getBasePath(), t);
        }
      }
    } finally {
      SYNCING.remove();
    }
  }

  @Override
  public void onFailure(String funcName, QueryExecution qe, Exception exception) {
    // No-op: only successful writes trigger a sync.
  }

  private List<TableSyncSpec> specs(SparkSession session) {
    List<TableSyncSpec> local = specs;
    if (local == null) {
      synchronized (this) {
        local = specs;
        if (local == null) {
          local = XTableSparkConfig.parse(confGetter(session), nameResolver(session));
          specs = local;
          log.info(
              "XTable spark-runtime configured for {} table(s): {}",
              local.size(),
              local.stream().map(TableSyncSpec::getKey).collect(Collectors.toList()));
        }
      }
    }
    return local;
  }

  private static UnaryOperator<String> confGetter(SparkSession session) {
    return key -> {
      try {
        return session.conf().get(key, null);
      } catch (Exception e) {
        return null;
      }
    };
  }

  private static UnaryOperator<String> nameResolver(SparkSession session) {
    return name -> {
      try {
        TableIdentifier id = session.sessionState().sqlParser().parseTableIdentifier(name);
        CatalogTable meta = session.sessionState().catalog().getTableMetadata(id);
        scala.Option<URI> location = meta.storage().locationUri();
        if (location.isDefined()) {
          return location.get().toString();
        }
        throw new IllegalArgumentException("No location URI for table '" + name + "'");
      } catch (RuntimeException e) {
        throw e;
      } catch (Exception e) {
        throw new IllegalArgumentException("Failed to resolve table '" + name + "' via catalog", e);
      }
    };
  }

  private static SparkSession activeSession() {
    scala.Option<SparkSession> active = SparkSession.getActiveSession();
    if (active.isDefined()) {
      return active.get();
    }
    scala.Option<SparkSession> dflt = SparkSession.getDefaultSession();
    return dflt.isDefined() ? dflt.get() : null;
  }

  /** Lenient path match ignoring scheme, trailing slashes, and partition sub-paths. */
  static boolean pathsMatch(String written, String configured) {
    URI a = new Path(written).toUri();
    URI b = new Path(configured).toUri();
    String pa = stripTrailingSlash(a.getPath());
    String pb = stripTrailingSlash(b.getPath());
    boolean pathRelated = pa.equals(pb) || pa.startsWith(pb + "/") || pb.startsWith(pa + "/");
    if (!pathRelated) {
      return false;
    }
    if (a.getAuthority() != null && b.getAuthority() != null) {
      return a.getAuthority().equals(b.getAuthority());
    }
    return true;
  }

  private static String stripTrailingSlash(String p) {
    if (p == null) {
      return "";
    }
    return (p.length() > 1 && p.endsWith("/")) ? p.substring(0, p.length() - 1) : p;
  }
}
