on:
  push:
    tags:
      - 'release-v*'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::194159489498:role/GithubActionsPublishHudi-RepositoryPublisherRole-10H7ABJVFNSQ9
          role-session-name: HudiPublishSession
          role-duration-seconds: 900
      - name: Set Env
        run: echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain onehouse --domain-owner 194159489498 --query authorizationToken --output text)" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: maven
          server-id: codeartifact
          server-username: AWS
          server-password: CODEARTIFACT_AUTH_TOKEN
      - name: Set TAG_PRESENT_IN_COMMIT
        run: echo "TAG_PRESENT_IN_COMMIT=$(git tag --contains $COMMIT_HASH | head -1)" >> $GITHUB_ENV
      - name: Set VERSION
        run: echo "VERSION=$(echo $TAG_PRESENT_IN_COMMIT | sed -e s/release-v//)" >> $GITHUB_ENV
      - name: Print Version
        run: echo "$VERSION"
      - name: Fail if version not set
        if: env.VERSION == ''
        run: exit 1
      - name: Set java version
        run: mvn versions:set -DnewVersion="$VERSION"
      - name: Deploy
        run: mvn -B -ntp -am -pl core deploy -DskipTests